#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Fri Oct 17 16:53:35 2025 from "/home/jan/local/home/jan/development/cad/KiCad-Spice-Library-master/Scripts/Gui.wxg"
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from NbListControl import NbListCtrlPanel, log
# end wxGlade


class SearchFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SearchFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((852, 691))
        self.SetTitle("model search")

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)

        self.nb_search = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_search, "search")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 0, wx.EXPAND | wx.TOP, 2)

        label_1 = wx.StaticText(self.nb_search, wx.ID_ANY, "search")
        sizer_5.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 0)

        self.search_ctrl_1 = wx.SearchCtrl(self.nb_search, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.search_ctrl_1.ShowCancelButton(True)
        sizer_5.Add(self.search_ctrl_1, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.start_search = wx.Button(self.nb_search, wx.ID_ANY, "search")
        sizer_5.Add(self.start_search, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.button_clear = wx.Button(self.nb_search, wx.ID_ANY, "clear")
        sizer_5.Add(self.button_clear, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.panel_list_search = NbListCtrlPanel(self.nb_search, ['name', 'type',  'file'] , log)
        sizer_1.Add(self.panel_list_search, 1, wx.EXPAND, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_15, 0, wx.ALL | wx.EXPAND, 2)

        label_8 = wx.StaticText(self.nb_search, wx.ID_ANY, "Number of models")
        sizer_15.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_search_count = wx.TextCtrl(self.nb_search, wx.ID_ANY, "0")
        sizer_15.Add(self.text_ctrl_search_count, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_content = wx.TextCtrl(self.nb_search, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        sizer_1.Add(self.text_ctrl_content, 2, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_6, 0, wx.FIXED_MINSIZE, 0)

        self.checkbox_recursive = wx.CheckBox(self.nb_search, wx.ID_ANY, "recursive (in subckt)")
        sizer_6.Add(self.checkbox_recursive, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.checkbox_model = wx.CheckBox(self.nb_search, wx.ID_ANY, "model")
        self.checkbox_model.SetValue(1)
        sizer_6.Add(self.checkbox_model, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.checkbox_subckt = wx.CheckBox(self.nb_search, wx.ID_ANY, "subckt")
        self.checkbox_subckt.SetValue(1)
        sizer_6.Add(self.checkbox_subckt, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.nb_models = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_models, "models")

        sizer_11 = wx.BoxSizer(wx.VERTICAL)

        self.panel_list_models = NbListCtrlPanel(self.nb_models, ['name', 'count'] , log)
        sizer_11.Add(self.panel_list_models, 1, wx.EXPAND, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(sizer_7, 0, wx.FIXED_MINSIZE, 0)

        label_4 = wx.StaticText(self.nb_models, wx.ID_ANY, "total number of models")
        sizer_7.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_number_of_models = wx.TextCtrl(self.nb_models, wx.ID_ANY, "0")
        sizer_7.Add(self.text_ctrl_number_of_models, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.button_4 = wx.Button(self.nb_models, wx.ID_ANY, "clear model list")
        sizer_7.Add(self.button_4, 0, wx.ALL, 2)

        self.nb_extensions = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_extensions, "extensions")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.panel_list_extensions = NbListCtrlPanel(self.nb_extensions, ['extension', 'count'] , log)
        sizer_2.Add(self.panel_list_extensions, 1, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_12, 0, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.nb_extensions, wx.ID_ANY, "total number of extensions")
        sizer_12.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_number_of_extensions = wx.TextCtrl(self.nb_extensions, wx.ID_ANY, "0")
        sizer_12.Add(self.text_ctrl_number_of_extensions, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.button_3 = wx.Button(self.nb_extensions, wx.ID_ANY, "clear extension list")
        sizer_12.Add(self.button_3, 0, 0, 0)

        self.nb_files = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_files, "files")

        sizer_4 = wx.BoxSizer(wx.VERTICAL)

        self.panel_list_files = NbListCtrlPanel(self.nb_files, [ 'name', 'model count'] , log)
        sizer_4.Add(self.panel_list_files, 1, wx.EXPAND, 0)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(sizer_13, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.nb_files, wx.ID_ANY, "total numer of files")
        sizer_13.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_number_of_files = wx.TextCtrl(self.nb_files, wx.ID_ANY, "0")
        sizer_13.Add(self.text_ctrl_number_of_files, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.button_2 = wx.Button(self.nb_files, wx.ID_ANY, "clear files list")
        sizer_13.Add(self.button_2, 0, wx.ALL, 2)

        self.nb_folders = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_folders, "folders")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.panel_list_folders = NbListCtrlPanel(self.nb_folders, ['path', 'nr of files', 'nr of models'] , log)
        sizer_3.Add(self.panel_list_folders, 1, wx.EXPAND, 0)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_14, 0, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.nb_folders, wx.ID_ANY, "total number of folders")
        sizer_14.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_number_of_folders = wx.TextCtrl(self.nb_folders, wx.ID_ANY, "0")
        sizer_14.Add(self.text_ctrl_number_of_folders, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.button_1 = wx.Button(self.nb_folders, wx.ID_ANY, "clear folder list")
        sizer_14.Add(self.button_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.panel_config = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.panel_config, "configuration")

        sizer_8 = wx.BoxSizer(wx.VERTICAL)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_config, wx.ID_ANY, "search folder", style=wx.ALIGN_RIGHT)
        label_2.SetMinSize((160, 26))
        sizer_9.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 2)

        self.text_ctrl_search_folder = wx.TextCtrl(self.panel_config, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        sizer_9.Add(self.text_ctrl_search_folder, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.button_select_search_folder = wx.Button(self.panel_config, wx.ID_ANY, "...")
        sizer_9.Add(self.button_select_search_folder, 0, 0, 0)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_10, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_config, wx.ID_ANY, "destination folder", style=wx.ALIGN_RIGHT)
        label_3.SetMinSize((160, 26))
        sizer_10.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 2)

        self.text_ctrl_destination_folder = wx.TextCtrl(self.panel_config, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        sizer_10.Add(self.text_ctrl_destination_folder, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.button_destination_folder = wx.Button(self.panel_config, wx.ID_ANY, "...")
        sizer_10.Add(self.button_destination_folder, 0, 0, 0)

        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_16, 0, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_config, wx.ID_ANY, "maximum length of history", style=wx.ALIGN_RIGHT)
        label_9.SetMinSize((250, 18))
        sizer_16.Add(label_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.text_ctrl_history_length = wx.TextCtrl(self.panel_config, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.text_ctrl_history_length.SetToolTip("Gives the maximum history when clicking the loupe on the search panel.")
        sizer_16.Add(self.text_ctrl_history_length, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 2)

        self.panel_1 = wx.Panel(self.panel_config, wx.ID_ANY)
        sizer_8.Add(self.panel_1, 4, wx.ALL | wx.EXPAND, 2)

        self.panel_config.SetSizer(sizer_8)

        self.nb_folders.SetSizer(sizer_3)

        self.nb_files.SetSizer(sizer_4)

        self.nb_extensions.SetSizer(sizer_2)

        self.nb_models.SetSizer(sizer_11)

        self.nb_search.SetSizer(sizer_1)

        self.Layout()

        self.search_ctrl_1.Bind(wx.EVT_SEARCHCTRL_SEARCH_BTN, self.on_search)
        self.search_ctrl_1.Bind(wx.EVT_TEXT_ENTER, self.on_search)
        self.start_search.Bind(wx.EVT_BUTTON, self.on_search)
        self.button_clear.Bind(wx.EVT_BUTTON, self.on_clear)
        self.checkbox_recursive.Bind(wx.EVT_CHECKBOX, self.on_checkbox_recursive)
        self.checkbox_model.Bind(wx.EVT_CHECKBOX, self.on_checkbox_model)
        self.checkbox_subckt.Bind(wx.EVT_CHECKBOX, self.on_checkbox_subckt)
        self.button_4.Bind(wx.EVT_BUTTON, self.on_clear_model_list)
        self.button_3.Bind(wx.EVT_BUTTON, self.on_clear_extension_list)
        self.button_2.Bind(wx.EVT_BUTTON, self.on_clear_files_list)
        self.button_1.Bind(wx.EVT_BUTTON, self.on_clear_list_folders)
        self.text_ctrl_search_folder.Bind(wx.EVT_TEXT_ENTER, self.on_text_ctrl_search_folder_enter)
        self.button_select_search_folder.Bind(wx.EVT_BUTTON, self.on_search_folder)
        self.text_ctrl_destination_folder.Bind(wx.EVT_TEXT_ENTER, self.on_text_ctrl_destination_folder_enter)
        self.button_destination_folder.Bind(wx.EVT_BUTTON, self.on_destination_folder)
        self.text_ctrl_history_length.Bind(wx.EVT_TEXT_ENTER, self.on_text_ctrl_history_length)
        # end wxGlade

    def on_search(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_search' not implemented!")
        event.Skip()

    def on_clear(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_clear' not implemented!")
        event.Skip()

    def on_checkbox_recursive(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_checkbox_recursive' not implemented!")
        event.Skip()

    def on_checkbox_model(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_checkbox_model' not implemented!")
        event.Skip()

    def on_checkbox_subckt(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_checkbox_subckt' not implemented!")
        event.Skip()

    def on_clear_model_list(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_clear_model_list' not implemented!")
        event.Skip()

    def on_clear_extension_list(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_clear_extension_list' not implemented!")
        event.Skip()

    def on_clear_files_list(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_clear_files_list' not implemented!")
        event.Skip()

    def on_clear_list_folders(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_clear_list_folders' not implemented!")
        event.Skip()

    def on_text_ctrl_search_folder_enter(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_text_ctrl_search_folder_enter' not implemented!")
        event.Skip()

    def on_search_folder(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_search_folder' not implemented!")
        event.Skip()

    def on_text_ctrl_destination_folder_enter(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_text_ctrl_destination_folder_enter' not implemented!")
        event.Skip()

    def on_destination_folder(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_destination_folder' not implemented!")
        event.Skip()

    def on_text_ctrl_history_length(self, event):  # wxGlade: SearchFrame.<event_handler>
        print("Event handler 'on_text_ctrl_history_length' not implemented!")
        event.Skip()

# end of class SearchFrame

class SearchApp(wx.App):
    def OnInit(self):
        self.frame = SearchFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class SearchApp

if __name__ == "__main__":
    app = SearchApp(0)
    app.MainLoop()
